//! Linux L3 netlink primitives for Gate 9 symmetric IRB (RFC 9136
//! §4.4.2). Three apply functions, one per kernel object the L3
//! install pipeline writes:
//!
//! 1. [`apply_add_ip_route`] / [`apply_remove_ip_route`] — the
//!    per-IP-VRF `ip route replace <prefix> table <table_id> via
//!    <next_hop> dev <l3vxlan> proto bgp onlink` row.
//! 2. [`apply_add_l3_neighbor`] / [`apply_remove_l3_neighbor`] —
//!    the `(next_hop → router_mac)` permanent ARP/ND entry on the
//!    L3 VXLAN device. The kernel uses this to fill the inner
//!    Ethernet header when encapsulating routed traffic.
//! 3. [`apply_add_l3vxlan_fdb`] / [`apply_remove_l3vxlan_fdb`] —
//!    the `(router_mac → next_hop)` FDB row on the L3 VXLAN device
//!    itself. With this entry present the VXLAN driver picks the
//!    right tunnel endpoint when it sees the inner DMAC.
//!
//! All three are dispatched by [`crate::LinuxDataplane::apply`] from
//! `DataplaneOp` variants generated by the reconcile actor's L3
//! diff loop. Refcounting on the shared neighbor/FDB rows
//! (`(IpVrfId, vtep_ip, router_mac)` may be referenced by multiple
//! prefixes) lives in the reconcile actor, not here.
//!
//! ## `RTPROT_BGP` + `RTNH_F_ONLINK`
//!
//! - `RTPROT_BGP` keeps slice 6a's local-route observer from
//!   re-originating routes we just installed from EVPN. The
//!   classifier in `linux/routes.rs` drops `RouteProtocol::Bgp`
//!   exactly because of this marker.
//! - `RTNH_F_ONLINK` tells the kernel to skip the
//!   "is the next-hop reachable via the output device?" check on
//!   FIB install. The L3 VXLAN device does not have a route to the
//!   remote VTEP — that's the underlay's job, not the L3VXLAN's —
//!   so without `onlink` the kernel would reject the route.
//!
//! ## Family mismatch
//!
//! Cross-family routes (IPv6 prefix over IPv4 VTEP next-hop or vice
//! versa) require `RTA_VIA` for the cross-family gateway encoding,
//! which this slice does not implement. The reconcile actor's
//! projection layer drops such routes before they reach an op; if
//! one slips through, [`apply_add_ip_route`] guards with an
//! `InvalidArgument` rather than silently programming a same-family
//! route with the wrong gateway type.

use std::net::IpAddr;

use netlink_packet_route::AddressFamily;
use netlink_packet_route::neighbour::{
    NeighbourAttribute, NeighbourFlags, NeighbourMessage, NeighbourState,
};
use netlink_packet_route::route::{
    RouteAddress, RouteAttribute, RouteFlags, RouteHeader, RouteMessage, RouteProtocol, RouteScope,
    RouteType,
};
use rtnetlink::Handle;
use rustbgpd_evpn::{EvpnIpPrefixValue, MacAddress};

use super::fdb::{classify_apply_error, classify_remove_apply_error};
use crate::error::DataplaneError;

/// `RT_TABLE_COMPAT` — the kernel UAPI sentinel
/// (`<linux/rtnetlink.h>`) that tells dump-side parsers "the real
/// 32-bit table id rides in `RouteAttribute::Table`." Used as the
/// `header.table` byte for any IP-VRF whose `table_id ≥ 256`.
/// `netlink-packet-route` 0.30 doesn't expose this constant
/// directly; inlining the well-known uapi value keeps the apply
/// path self-contained.
const RT_TABLE_COMPAT: u8 = 252;

/// `NUD_NOARP` — neighbor entries in this state do not participate
/// in ARP/ND resolution (we already know the MAC, no need to
/// solicit).
const NUD_NOARP: u16 = 0x40;
/// `NUD_PERMANENT` — non-aging neighbor entry.
const NUD_PERMANENT: u16 = 0x80;
/// `NUD_NOARP | NUD_PERMANENT` — the kernel state bitmask for
/// non-expiring control-plane-owned entries (what iproute2 emits
/// for `bridge fdb add ... extern_learn`). Mirrors the fdb-helper
/// constant so the L2 and L3 paths use the same shape.
const NUD_NOARP_PERMANENT: u16 = NUD_NOARP | NUD_PERMANENT;

/// Install (or replace) a kernel route for a remote IP prefix in
/// the IP-VRF's `table_id`.
///
/// # Errors
///
/// Returns [`DataplaneError::InvalidArgument`] if the prefix and
/// next-hop disagree on address family. Any other failure is
/// classified by [`classify_apply_error`].
pub(crate) async fn apply_add_ip_route(
    handle: &Handle,
    prefix: EvpnIpPrefixValue,
    table_id: u32,
    l3vxlan_ifindex: u32,
    next_hop: IpAddr,
) -> Result<(), DataplaneError> {
    let msg = build_ip_route_message(prefix, table_id, l3vxlan_ifindex, next_hop)?;
    handle
        .route()
        .add(msg)
        .replace()
        .execute()
        .await
        .map_err(|e| classify_apply_error(&e))
}

/// Remove a previously-installed remote IP-prefix route.
///
/// # Errors
///
/// Returns [`DataplaneError::InvalidArgument`] on family mismatch.
/// Other failures classify per [`classify_remove_apply_error`],
/// which treats `ENOENT` as idempotent success — if the kernel
/// row is already absent the post-condition holds and the actor
/// should advance `L3OwnedState` rather than retry forever.
pub(crate) async fn apply_remove_ip_route(
    handle: &Handle,
    prefix: EvpnIpPrefixValue,
    table_id: u32,
    l3vxlan_ifindex: u32,
    next_hop: IpAddr,
) -> Result<(), DataplaneError> {
    let msg = build_ip_route_message(prefix, table_id, l3vxlan_ifindex, next_hop)?;
    match handle.route().del(msg).execute().await {
        Ok(()) => Ok(()),
        Err(e) => classify_remove_apply_error(&e),
    }
}

fn build_ip_route_message(
    prefix: EvpnIpPrefixValue,
    table_id: u32,
    l3vxlan_ifindex: u32,
    next_hop: IpAddr,
) -> Result<RouteMessage, DataplaneError> {
    let prefix_family = match prefix {
        EvpnIpPrefixValue::V4(_) => AddressFamily::Inet,
        EvpnIpPrefixValue::V6(_) => AddressFamily::Inet6,
    };
    let nh_family = match next_hop {
        IpAddr::V4(_) => AddressFamily::Inet,
        IpAddr::V6(_) => AddressFamily::Inet6,
    };
    if prefix_family != nh_family {
        return Err(DataplaneError::InvalidArgument(format!(
            "Gate 9 slice 6c does not implement cross-family IP-prefix routes \
             (prefix family {prefix_family:?} vs next-hop family {nh_family:?}); \
             reconciler should drop the route before generating an op"
        )));
    }

    let mut msg = RouteMessage::default();
    msg.header = RouteHeader {
        address_family: prefix_family,
        destination_prefix_length: match prefix {
            EvpnIpPrefixValue::V4(p) => p.len,
            EvpnIpPrefixValue::V6(p) => p.len,
        },
        source_prefix_length: 0,
        tos: 0,
        // `table` is u8. Kernel >= 2.6.19 reads the full 32-bit table
        // id from `RouteAttribute::Table` when present, falling back
        // to header.table otherwise. Set the compat sentinel (252)
        // when table_id ≥ 256 so older kernels and dump-side parsers
        // see the conventional out-of-band marker.
        table: u8::try_from(table_id).unwrap_or(RT_TABLE_COMPAT),
        // `RTPROT_BGP` (186) so slice 6a's local-route observer
        // never re-originates routes we installed from EVPN. The
        // classifier in `linux/routes.rs` drops this protocol.
        protocol: RouteProtocol::Bgp,
        scope: RouteScope::Universe,
        kind: RouteType::Unicast,
        // `RTNH_F_ONLINK` — see module-level docs for why the
        // recursive lookup must be suppressed for the L3VXLAN case.
        flags: RouteFlags::Onlink,
    };
    // Always emit `RouteAttribute::Table` for tables ≥ 256;
    // including it for smaller tables too is harmless and keeps
    // the apply path uniform.
    msg.attributes.push(RouteAttribute::Table(table_id));
    msg.attributes
        .push(RouteAttribute::Destination(match prefix {
            EvpnIpPrefixValue::V4(p) => RouteAddress::Inet(p.addr),
            EvpnIpPrefixValue::V6(p) => RouteAddress::Inet6(p.addr),
        }));
    msg.attributes.push(RouteAttribute::Gateway(match next_hop {
        IpAddr::V4(a) => RouteAddress::Inet(a),
        IpAddr::V6(a) => RouteAddress::Inet6(a),
    }));
    msg.attributes.push(RouteAttribute::Oif(l3vxlan_ifindex));
    Ok(msg)
}

/// Add (or replace) a permanent ARP/ND entry on the L3 VXLAN
/// device mapping the remote VTEP IP to the remote PE's router MAC.
/// This is what the kernel consults when building the inner
/// Ethernet header during symmetric-IRB encapsulation.
///
/// # Errors
///
/// Failures classify per [`classify_apply_error`]. `EEXIST` is
/// idempotent and surfaces as transient (the actor's permanent-
/// failure suppression handles the no-op convergence).
pub(crate) async fn apply_add_l3_neighbor(
    handle: &Handle,
    l3vxlan_ifindex: u32,
    next_hop: IpAddr,
    router_mac: MacAddress,
) -> Result<(), DataplaneError> {
    handle
        .neighbours()
        .add(l3vxlan_ifindex, next_hop)
        .link_layer_address(&router_mac.octets())
        .state(NeighbourState::Permanent)
        .flags(NeighbourFlags::ExtLearned)
        .replace()
        .execute()
        .await
        .map_err(|e| classify_apply_error(&e))
}

/// Remove a previously-installed L3 neighbor entry.
///
/// # Errors
///
/// Failures classify per [`classify_remove_apply_error`] —
/// `ENOENT` is idempotent success so a foreign delete or prior
/// partial drain doesn't wedge `L3OwnedState` convergence.
pub(crate) async fn apply_remove_l3_neighbor(
    handle: &Handle,
    l3vxlan_ifindex: u32,
    next_hop: IpAddr,
) -> Result<(), DataplaneError> {
    let mut msg = NeighbourMessage::default();
    msg.header.family = match next_hop {
        IpAddr::V4(_) => AddressFamily::Inet,
        IpAddr::V6(_) => AddressFamily::Inet6,
    };
    msg.header.ifindex = l3vxlan_ifindex;
    msg.header.state = NeighbourState::Permanent;
    msg.header.kind = RouteType::Unspec;
    msg.attributes
        .push(NeighbourAttribute::Destination(match next_hop {
            IpAddr::V4(a) => netlink_packet_route::neighbour::NeighbourAddress::Inet(a),
            IpAddr::V6(a) => netlink_packet_route::neighbour::NeighbourAddress::Inet6(a),
        }));
    match handle.neighbours().del(msg).execute().await {
        Ok(()) => Ok(()),
        Err(e) => classify_remove_apply_error(&e),
    }
}

/// Add (or replace) the FDB row on the L3 VXLAN device that maps
/// the remote PE's router MAC to the remote VTEP IP. The VXLAN
/// driver consults this to pick the right tunnel endpoint when it
/// sees the inner DMAC during encapsulation.
///
/// Unlike L2 FDB programming, an L3 VXLAN is **not** enslaved to a
/// bridge — it's a slave of a VRF master device. The FDB row
/// therefore carries only `NTF_SELF` (no `NTF_MASTER`), matching
/// what iproute2 emits for `bridge fdb add ... dev l3vxlanX self`.
///
/// # Errors
///
/// Failures classify per [`classify_apply_error`]. `EEXIST` is
/// idempotent.
pub(crate) async fn apply_add_l3vxlan_fdb(
    handle: &Handle,
    l3vxlan_ifindex: u32,
    router_mac: MacAddress,
    next_hop: IpAddr,
) -> Result<(), DataplaneError> {
    handle
        .neighbours()
        .add_bridge(l3vxlan_ifindex, &router_mac.octets())
        .destination(next_hop)
        .state(NeighbourState::Other(NUD_NOARP_PERMANENT))
        .flags(NeighbourFlags::Own | NeighbourFlags::ExtLearned)
        .replace()
        .execute()
        .await
        .map_err(|e| classify_apply_error(&e))
}

/// Remove a previously-installed L3VXLAN FDB row.
///
/// # Errors
///
/// Failures classify per [`classify_remove_apply_error`] —
/// `ENOENT` is idempotent success so a foreign `bridge fdb del`
/// or prior partial drain doesn't wedge `L3OwnedState`.
pub(crate) async fn apply_remove_l3vxlan_fdb(
    handle: &Handle,
    l3vxlan_ifindex: u32,
    router_mac: MacAddress,
) -> Result<(), DataplaneError> {
    let mut msg = NeighbourMessage::default();
    msg.header.family = AddressFamily::Bridge;
    msg.header.ifindex = l3vxlan_ifindex;
    msg.header.kind = RouteType::Unspec;
    msg.header.flags = NeighbourFlags::Own;
    msg.attributes.push(NeighbourAttribute::LinkLayerAddress(
        router_mac.octets().to_vec(),
    ));
    match handle.neighbours().del(msg).execute().await {
        Ok(()) => Ok(()),
        Err(e) => classify_remove_apply_error(&e),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use rustbgpd_evpn::{Ipv4Prefix, Ipv6Prefix};
    use std::net::{Ipv4Addr, Ipv6Addr};

    fn v4_prefix(addr: [u8; 4], len: u8) -> EvpnIpPrefixValue {
        EvpnIpPrefixValue::V4(Ipv4Prefix::new(Ipv4Addr::from(addr), len))
    }

    fn v6_prefix(segs: [u16; 8], len: u8) -> EvpnIpPrefixValue {
        let a = Ipv6Addr::new(
            segs[0], segs[1], segs[2], segs[3], segs[4], segs[5], segs[6], segs[7],
        );
        EvpnIpPrefixValue::V6(Ipv6Prefix::new(a, len))
    }

    #[test]
    fn build_v4_route_carries_onlink_proto_bgp_and_table() {
        let prefix = v4_prefix([198, 51, 100, 0], 24);
        let nh = IpAddr::V4(Ipv4Addr::new(10, 0, 0, 2));
        let msg = build_ip_route_message(prefix, 100, 42, nh).unwrap();
        assert_eq!(msg.header.address_family, AddressFamily::Inet);
        assert_eq!(msg.header.destination_prefix_length, 24);
        assert_eq!(msg.header.protocol, RouteProtocol::Bgp);
        assert_eq!(msg.header.scope, RouteScope::Universe);
        assert_eq!(msg.header.kind, RouteType::Unicast);
        assert!(
            msg.header.flags.contains(RouteFlags::Onlink),
            "RTNH_F_ONLINK must be set so the kernel skips the recursive lookup"
        );
        assert_eq!(msg.header.table, 100);

        let table_attr = msg.attributes.iter().find_map(|a| match a {
            RouteAttribute::Table(t) => Some(*t),
            _ => None,
        });
        assert_eq!(table_attr, Some(100));

        let dst = msg.attributes.iter().find_map(|a| match a {
            RouteAttribute::Destination(d) => Some(d.clone()),
            _ => None,
        });
        assert!(matches!(dst, Some(RouteAddress::Inet(_))));

        let gw = msg.attributes.iter().find_map(|a| match a {
            RouteAttribute::Gateway(g) => Some(g.clone()),
            _ => None,
        });
        assert!(matches!(gw, Some(RouteAddress::Inet(addr)) if addr == Ipv4Addr::new(10,0,0,2)));

        let oif = msg.attributes.iter().find_map(|a| match a {
            RouteAttribute::Oif(idx) => Some(*idx),
            _ => None,
        });
        assert_eq!(oif, Some(42));
    }

    #[test]
    fn build_v6_route_uses_inet6_family() {
        let prefix = v6_prefix([0x2001, 0xdb8, 0, 0, 0, 0, 0, 0], 64);
        let nh = IpAddr::V6(Ipv6Addr::new(0xfd00, 0, 0, 0, 0, 0, 0, 1));
        let msg = build_ip_route_message(prefix, 200, 7, nh).unwrap();
        assert_eq!(msg.header.address_family, AddressFamily::Inet6);
        assert_eq!(msg.header.destination_prefix_length, 64);
        assert!(msg.header.flags.contains(RouteFlags::Onlink));
    }

    #[test]
    fn build_route_uses_rt_table_compat_for_large_table_ids() {
        let prefix = v4_prefix([198, 51, 100, 0], 24);
        let nh = IpAddr::V4(Ipv4Addr::new(10, 0, 0, 2));
        let msg = build_ip_route_message(prefix, 50_000, 42, nh).unwrap();
        assert_eq!(msg.header.table, RT_TABLE_COMPAT);
        // The full id rides in the attribute so the kernel reads
        // the real table.
        let table_attr = msg.attributes.iter().find_map(|a| match a {
            RouteAttribute::Table(t) => Some(*t),
            _ => None,
        });
        assert_eq!(table_attr, Some(50_000));
    }

    #[test]
    fn family_mismatch_rejected_at_build_time() {
        // IPv4 prefix, IPv6 next-hop → must error rather than
        // silently miscompose. The reconciler's projection layer
        // catches this earlier; this is defense-in-depth.
        let prefix = v4_prefix([198, 51, 100, 0], 24);
        let nh = IpAddr::V6(Ipv6Addr::new(0xfd00, 0, 0, 0, 0, 0, 0, 1));
        let err = build_ip_route_message(prefix, 100, 42, nh).unwrap_err();
        assert!(matches!(err, DataplaneError::InvalidArgument(_)));
    }
}
