//! Linux L3 netlink primitives for Gate 9 symmetric IRB (RFC 9136
//! §4.4.2). Three apply functions, one per kernel object the L3
//! install pipeline writes:
//!
//! 1. [`apply_add_ip_route`] / [`apply_remove_ip_route`] — the
//!    per-IP-VRF `ip route replace <prefix> table <table_id> via
//!    <next_hop> dev <l3vxlan> proto bgp onlink` row.
//! 2. [`apply_add_l3_neighbor`] / [`apply_remove_l3_neighbor`] —
//!    the `(next_hop → router_mac)` permanent ARP/ND entry on the
//!    L3 VXLAN device. The kernel uses this to fill the inner
//!    Ethernet header when encapsulating routed traffic.
//! 3. [`apply_add_l3vxlan_fdb`] / [`apply_remove_l3vxlan_fdb`] —
//!    the `(router_mac → next_hop)` FDB row on the L3 VXLAN device
//!    itself. With this entry present the VXLAN driver picks the
//!    right tunnel endpoint when it sees the inner DMAC.
//!
//! All three are dispatched by [`crate::LinuxDataplane::apply`] from
//! `DataplaneOp` variants generated by the reconcile actor's L3
//! diff loop. Refcounting on the shared neighbor/FDB rows
//! (`(IpVrfId, vtep_ip, router_mac)` may be referenced by multiple
//! prefixes) lives in the reconcile actor, not here.
//!
//! ## `RTPROT_BGP` + `RTNH_F_ONLINK`
//!
//! - `RTPROT_BGP` keeps slice 6a's local-route observer from
//!   re-originating routes we just installed from EVPN. The
//!   classifier in `linux/routes.rs` drops `RouteProtocol::Bgp`
//!   exactly because of this marker.
//! - `RTNH_F_ONLINK` tells the kernel to skip the
//!   "is the next-hop reachable via the output device?" check on
//!   FIB install. The L3 VXLAN device does not have a route to the
//!   remote VTEP — that's the underlay's job, not the L3VXLAN's —
//!   so without `onlink` the kernel would reject the route.
//!
//! ## Family mismatch
//!
//! Cross-family routes (IPv6 prefix over IPv4 VTEP next-hop or vice
//! versa) require `RTA_VIA` for the cross-family gateway encoding,
//! which this slice does not implement. The reconcile actor's
//! projection layer drops such routes before they reach an op; if
//! one slips through, [`apply_add_ip_route`] guards with an
//! `InvalidArgument` rather than silently programming a same-family
//! route with the wrong gateway type.

use std::net::IpAddr;
use std::sync::atomic::{AtomicBool, Ordering};

use netlink_packet_core::DefaultNla;
use netlink_packet_route::AddressFamily;
use netlink_packet_route::neighbour::{
    NeighbourAddress, NeighbourAttribute, NeighbourFlags, NeighbourMessage, NeighbourState,
};
use netlink_packet_route::route::{
    RouteAddress, RouteAttribute, RouteFlags, RouteHeader, RouteMessage, RouteNextHop,
    RouteNextHopFlags, RouteProtocol, RouteScope, RouteType,
};
use rtnetlink::Handle;
use rustbgpd_evpn::{EvpnIpPrefixValue, MacAddress};

use super::fdb::{classify_apply_error, classify_remove_apply_error, is_einval};
use crate::error::DataplaneError;

/// `RT_TABLE_COMPAT` — the kernel UAPI sentinel
/// (`<linux/rtnetlink.h>`) that tells dump-side parsers "the real
/// 32-bit table id rides in `RouteAttribute::Table`." Used as the
/// `header.table` byte for any IP-VRF whose `table_id ≥ 256`.
/// `netlink-packet-route` 0.30 doesn't expose this constant
/// directly; inlining the well-known uapi value keeps the apply
/// path self-contained.
const RT_TABLE_COMPAT: u8 = 252;

/// `NUD_NOARP` — neighbor entries in this state do not participate
/// in ARP/ND resolution (we already know the MAC, no need to
/// solicit).
const NUD_NOARP: u16 = 0x40;
/// `NUD_PERMANENT` — non-aging neighbor entry.
const NUD_PERMANENT: u16 = 0x80;
/// `NUD_NOARP | NUD_PERMANENT` — the kernel state bitmask for
/// non-expiring control-plane-owned entries (what iproute2 emits
/// for `bridge fdb add ... extern_learn`). Mirrors the fdb-helper
/// constant so the L2 and L3 paths use the same shape.
const NUD_NOARP_PERMANENT: u16 = NUD_NOARP | NUD_PERMANENT;
/// `NDA_NH_ID` (kind = 13). Exposed in iproute2 as `bridge fdb ...
/// nhid N`; `netlink-packet-route 0.30` keeps it behind the raw NLA
/// escape hatch.
const NDA_NH_ID: u16 = 13;

/// Install (or replace) a kernel route for a remote IP prefix in
/// the IP-VRF's `table_id`.
///
/// # Errors
///
/// Returns [`DataplaneError::InvalidArgument`] if the prefix and
/// next-hop disagree on address family. Any other failure is
/// classified by [`classify_apply_error`].
pub(crate) async fn apply_add_ip_route(
    handle: &Handle,
    prefix: EvpnIpPrefixValue,
    table_id: u32,
    l3vxlan_ifindex: u32,
    next_hop: IpAddr,
) -> Result<(), DataplaneError> {
    let msg = build_ip_route_message(prefix, table_id, l3vxlan_ifindex, next_hop)?;
    handle
        .route()
        .add(msg)
        .replace()
        .execute()
        .await
        .map_err(|e| classify_apply_error(&e))
}

/// Remove a previously-installed remote IP-prefix route.
///
/// # Errors
///
/// Returns [`DataplaneError::InvalidArgument`] on family mismatch.
/// Other failures classify per [`classify_remove_apply_error`],
/// which treats `ENOENT` as idempotent success — if the kernel
/// row is already absent the post-condition holds and the actor
/// should advance `L3OwnedState` rather than retry forever.
pub(crate) async fn apply_remove_ip_route(
    handle: &Handle,
    prefix: EvpnIpPrefixValue,
    table_id: u32,
    l3vxlan_ifindex: u32,
    next_hop: IpAddr,
) -> Result<(), DataplaneError> {
    let msg = build_ip_route_message(prefix, table_id, l3vxlan_ifindex, next_hop)?;
    match handle.route().del(msg).execute().await {
        Ok(()) => Ok(()),
        Err(e) => classify_remove_apply_error(&e),
    }
}

/// Install (or replace) an ECMP kernel route for an all-active ESI
/// overlay-index Type 5 prefix in the IP-VRF's `table_id`.
///
/// # Errors
///
/// Returns [`DataplaneError::InvalidArgument`] if the target set is
/// empty or if any next-hop disagrees with the prefix family. Any
/// other failure is classified by [`classify_apply_error`].
pub(crate) async fn apply_add_ip_route_ecmp(
    handle: &Handle,
    prefix: EvpnIpPrefixValue,
    table_id: u32,
    l3vxlan_ifindex: u32,
    next_hops: &[IpAddr],
) -> Result<(), DataplaneError> {
    let msg = build_ip_route_ecmp_message(prefix, table_id, l3vxlan_ifindex, next_hops)?;
    handle
        .route()
        .add(msg)
        .replace()
        .execute()
        .await
        .map_err(|e| classify_apply_error(&e))
}

/// Remove a previously-installed all-active ECMP remote IP-prefix route.
///
/// # Errors
///
/// Returns [`DataplaneError::InvalidArgument`] on invalid target set
/// shape. Other failures classify per [`classify_remove_apply_error`],
/// which treats `ENOENT` as idempotent success.
pub(crate) async fn apply_remove_ip_route_ecmp(
    handle: &Handle,
    prefix: EvpnIpPrefixValue,
    table_id: u32,
    l3vxlan_ifindex: u32,
    next_hops: &[IpAddr],
) -> Result<(), DataplaneError> {
    let msg = build_ip_route_ecmp_message(prefix, table_id, l3vxlan_ifindex, next_hops)?;
    match handle.route().del(msg).execute().await {
        Ok(()) => Ok(()),
        Err(e) => classify_remove_apply_error(&e),
    }
}

fn build_ip_route_message(
    prefix: EvpnIpPrefixValue,
    table_id: u32,
    l3vxlan_ifindex: u32,
    next_hop: IpAddr,
) -> Result<RouteMessage, DataplaneError> {
    let prefix_family = match prefix {
        EvpnIpPrefixValue::V4(_) => AddressFamily::Inet,
        EvpnIpPrefixValue::V6(_) => AddressFamily::Inet6,
    };
    let nh_family = match next_hop {
        IpAddr::V4(_) => AddressFamily::Inet,
        IpAddr::V6(_) => AddressFamily::Inet6,
    };
    if prefix_family != nh_family {
        return Err(DataplaneError::InvalidArgument(format!(
            "Gate 9 slice 6c does not implement cross-family IP-prefix routes \
             (prefix family {prefix_family:?} vs next-hop family {nh_family:?}); \
             reconciler should drop the route before generating an op"
        )));
    }

    let mut msg = RouteMessage::default();
    msg.header = RouteHeader {
        address_family: prefix_family,
        destination_prefix_length: match prefix {
            EvpnIpPrefixValue::V4(p) => p.len,
            EvpnIpPrefixValue::V6(p) => p.len,
        },
        source_prefix_length: 0,
        tos: 0,
        // `table` is u8. Kernel >= 2.6.19 reads the full 32-bit table
        // id from `RouteAttribute::Table` when present, falling back
        // to header.table otherwise. Set the compat sentinel (252)
        // when table_id ≥ 256 so older kernels and dump-side parsers
        // see the conventional out-of-band marker.
        table: u8::try_from(table_id).unwrap_or(RT_TABLE_COMPAT),
        // `RTPROT_BGP` (186) so slice 6a's local-route observer
        // never re-originates routes we installed from EVPN. The
        // classifier in `linux/routes.rs` drops this protocol.
        protocol: RouteProtocol::Bgp,
        scope: RouteScope::Universe,
        kind: RouteType::Unicast,
        // `RTNH_F_ONLINK` — see module-level docs for why the
        // recursive lookup must be suppressed for the L3VXLAN case.
        flags: RouteFlags::Onlink,
    };
    // Always emit `RouteAttribute::Table` for tables ≥ 256;
    // including it for smaller tables too is harmless and keeps
    // the apply path uniform.
    msg.attributes.push(RouteAttribute::Table(table_id));
    msg.attributes
        .push(RouteAttribute::Destination(match prefix {
            EvpnIpPrefixValue::V4(p) => RouteAddress::Inet(p.addr),
            EvpnIpPrefixValue::V6(p) => RouteAddress::Inet6(p.addr),
        }));
    msg.attributes.push(RouteAttribute::Gateway(match next_hop {
        IpAddr::V4(a) => RouteAddress::Inet(a),
        IpAddr::V6(a) => RouteAddress::Inet6(a),
    }));
    msg.attributes.push(RouteAttribute::Oif(l3vxlan_ifindex));
    Ok(msg)
}

fn build_ip_route_ecmp_message(
    prefix: EvpnIpPrefixValue,
    table_id: u32,
    l3vxlan_ifindex: u32,
    next_hops: &[IpAddr],
) -> Result<RouteMessage, DataplaneError> {
    if next_hops.len() < 2 {
        return Err(DataplaneError::InvalidArgument(
            "all-active Type 5 ECMP route requires at least two next-hops".into(),
        ));
    }
    let prefix_family = match prefix {
        EvpnIpPrefixValue::V4(_) => AddressFamily::Inet,
        EvpnIpPrefixValue::V6(_) => AddressFamily::Inet6,
    };
    for next_hop in next_hops {
        let nh_family = match next_hop {
            IpAddr::V4(_) => AddressFamily::Inet,
            IpAddr::V6(_) => AddressFamily::Inet6,
        };
        if prefix_family != nh_family {
            return Err(DataplaneError::InvalidArgument(format!(
                "all-active Type 5 ECMP route does not implement cross-family \
                 next-hops (prefix family {prefix_family:?} vs next-hop family {nh_family:?}); \
                 reconciler should drop the route before generating an op"
            )));
        }
    }

    let mut msg = RouteMessage::default();
    msg.header = RouteHeader {
        address_family: prefix_family,
        destination_prefix_length: match prefix {
            EvpnIpPrefixValue::V4(p) => p.len,
            EvpnIpPrefixValue::V6(p) => p.len,
        },
        source_prefix_length: 0,
        tos: 0,
        table: u8::try_from(table_id).unwrap_or(RT_TABLE_COMPAT),
        protocol: RouteProtocol::Bgp,
        scope: RouteScope::Universe,
        kind: RouteType::Unicast,
        flags: RouteFlags::Onlink,
    };
    msg.attributes.push(RouteAttribute::Table(table_id));
    msg.attributes
        .push(RouteAttribute::Destination(match prefix {
            EvpnIpPrefixValue::V4(p) => RouteAddress::Inet(p.addr),
            EvpnIpPrefixValue::V6(p) => RouteAddress::Inet6(p.addr),
        }));
    let hops = next_hops
        .iter()
        .map(|next_hop| {
            let mut hop = RouteNextHop::default();
            hop.flags = RouteNextHopFlags::Onlink;
            hop.interface_index = l3vxlan_ifindex;
            hop.attributes.push(RouteAttribute::Gateway(match next_hop {
                IpAddr::V4(a) => RouteAddress::Inet(*a),
                IpAddr::V6(a) => RouteAddress::Inet6(*a),
            }));
            hop
        })
        .collect();
    msg.attributes.push(RouteAttribute::MultiPath(hops));
    Ok(msg)
}

/// Latched `true` once a kernel rejects the `NDA_PROTOCOL` ownership
/// stamp on an L3 neighbor install with `EINVAL` and the unstamped
/// retry succeeds (ADR-0082 decision 5: a strict-validation kernel
/// predating the neighbor protocol attribute, Linux < 5.0 — outside
/// the EVPN kernel baseline we test, but fail-soft). Subsequent
/// installs skip the stamp for the rest of the run; since the
/// ADR-0082 strict flip, adopting such unstamped rows after a crash
/// needs `RUSTBGPD_EVPN_ADOPTION_ACCEPT_LEGACY=1` (the warn below
/// says so once). Process-global on purpose: the capability is a
/// property of the running kernel, not of any one actor.
static L3_NEIGHBOR_STAMP_UNAVAILABLE: AtomicBool = AtomicBool::new(false);

/// Build the `RTM_NEWNEIGH` message for the permanent ARP/ND entry on
/// the L3 VXLAN device: `Permanent` state + `NTF_EXT_LEARNED`, and —
/// unless stamping has been latched unavailable — the ADR-0082
/// `NDA_PROTOCOL = RTPROT_BGP` ownership stamp. IP neighbors store and
/// echo the stamp since Linux 5.0, so `ip neigh show` reports
/// `proto bgp` on managed rows and the adoption sweep can tell our
/// rows from another controller's (zebra stamps `RTPROT_ZEBRA`).
fn build_l3_neighbor_message(
    l3vxlan_ifindex: u32,
    next_hop: IpAddr,
    router_mac: MacAddress,
    stamp: bool,
) -> NeighbourMessage {
    let mut msg = NeighbourMessage::default();
    msg.header.family = match next_hop {
        IpAddr::V4(_) => AddressFamily::Inet,
        IpAddr::V6(_) => AddressFamily::Inet6,
    };
    msg.header.ifindex = l3vxlan_ifindex;
    msg.header.state = NeighbourState::Permanent;
    msg.header.flags = NeighbourFlags::ExtLearned;
    msg.header.kind = RouteType::Unspec;
    msg.attributes
        .push(NeighbourAttribute::Destination(match next_hop {
            IpAddr::V4(a) => NeighbourAddress::Inet(a),
            IpAddr::V6(a) => NeighbourAddress::Inet6(a),
        }));
    msg.attributes.push(NeighbourAttribute::LinkLayerAddress(
        router_mac.octets().to_vec(),
    ));
    if stamp {
        msg.attributes
            .push(NeighbourAttribute::Protocol(RouteProtocol::Bgp));
    }
    msg
}

/// Add (or replace) a permanent ARP/ND entry on the L3 VXLAN
/// device mapping the remote VTEP IP to the remote PE's router MAC.
/// This is what the kernel consults when building the inner
/// Ethernet header during symmetric-IRB encapsulation.
///
/// Installs carry the ADR-0082 ownership stamp; if a stamped install
/// fails with `EINVAL` the kernel may be a strict-validation one
/// without the neighbor protocol attribute, so it is retried once
/// unstamped — on success, stamping is latched off for the rest of
/// the run (warned once). The errno alone cannot prove the attribute
/// caused the rejection; if the unstamped retry also fails, that
/// error propagates normally.
///
/// # Errors
///
/// Failures classify per [`classify_apply_error`]. `EEXIST` is
/// idempotent and surfaces as transient (the actor's permanent-
/// failure suppression handles the no-op convergence).
pub(crate) async fn apply_add_l3_neighbor(
    handle: &Handle,
    l3vxlan_ifindex: u32,
    next_hop: IpAddr,
    router_mac: MacAddress,
) -> Result<(), DataplaneError> {
    let stamp = !L3_NEIGHBOR_STAMP_UNAVAILABLE.load(Ordering::Relaxed);
    match send_l3_neighbor(handle, l3vxlan_ifindex, next_hop, router_mac, stamp).await {
        Ok(()) => Ok(()),
        Err(e) if stamp && is_einval(&e) => {
            send_l3_neighbor(handle, l3vxlan_ifindex, next_hop, router_mac, false)
                .await
                .map_err(|retry_err| classify_apply_error(&retry_err))?;
            if !L3_NEIGHBOR_STAMP_UNAVAILABLE.swap(true, Ordering::Relaxed) {
                tracing::warn!(
                    "kernel rejected the NDA_PROTOCOL ownership stamp on an L3 \
                     neighbor install (EINVAL) but accepted the unstamped retry; \
                     disabling stamping for the rest of this run — set \
                     RUSTBGPD_EVPN_ADOPTION_ACCEPT_LEGACY=1 so a restart can \
                     adopt this kernel's unstamped rows (ADR-0082)"
                );
            }
            Ok(())
        }
        Err(e) => Err(classify_apply_error(&e)),
    }
}

async fn send_l3_neighbor(
    handle: &Handle,
    l3vxlan_ifindex: u32,
    next_hop: IpAddr,
    router_mac: MacAddress,
    stamp: bool,
) -> Result<(), rtnetlink::Error> {
    let mut req = handle.neighbours().add(l3vxlan_ifindex, next_hop).replace();
    *req.message_mut() = build_l3_neighbor_message(l3vxlan_ifindex, next_hop, router_mac, stamp);
    req.execute().await
}

/// Remove a previously-installed L3 neighbor entry.
///
/// # Errors
///
/// Failures classify per [`classify_remove_apply_error`] —
/// `ENOENT` is idempotent success so a foreign delete or prior
/// partial drain doesn't wedge `L3OwnedState` convergence.
pub(crate) async fn apply_remove_l3_neighbor(
    handle: &Handle,
    l3vxlan_ifindex: u32,
    next_hop: IpAddr,
) -> Result<(), DataplaneError> {
    let mut msg = NeighbourMessage::default();
    msg.header.family = match next_hop {
        IpAddr::V4(_) => AddressFamily::Inet,
        IpAddr::V6(_) => AddressFamily::Inet6,
    };
    msg.header.ifindex = l3vxlan_ifindex;
    msg.header.state = NeighbourState::Permanent;
    msg.header.kind = RouteType::Unspec;
    msg.attributes
        .push(NeighbourAttribute::Destination(match next_hop {
            IpAddr::V4(a) => NeighbourAddress::Inet(a),
            IpAddr::V6(a) => NeighbourAddress::Inet6(a),
        }));
    match handle.neighbours().del(msg).execute().await {
        Ok(()) => Ok(()),
        Err(e) => classify_remove_apply_error(&e),
    }
}

/// Build the `RTM_NEWNEIGH` message for the L3VXLAN FDB row
/// (`router_mac → next_hop`), the `bridge fdb add ... dev l3vxlanX
/// self` shape with `NTF_SELF | NTF_EXT_LEARNED` and the combined
/// `NUD_NOARP | NUD_PERMANENT` state.
///
/// Carries the ADR-0082 `NDA_PROTOCOL = RTPROT_BGP` ownership stamp
/// unconditionally: `AF_BRIDGE` parses FDB adds with a NULL attribute
/// policy on mainline kernels, so the stamp is silently accepted and
/// dropped — it can never cause an `EINVAL` (no fallback needed) and
/// becomes effective automatically once kernel FDB support for the
/// attribute lands.
fn build_l3vxlan_fdb_message(
    l3vxlan_ifindex: u32,
    router_mac: MacAddress,
    next_hop: IpAddr,
) -> NeighbourMessage {
    let mut msg = NeighbourMessage::default();
    msg.header.family = AddressFamily::Bridge;
    msg.header.ifindex = l3vxlan_ifindex;
    msg.header.state = NeighbourState::Other(NUD_NOARP_PERMANENT);
    msg.header.flags = NeighbourFlags::Own | NeighbourFlags::ExtLearned;
    msg.header.kind = RouteType::Unspec;
    msg.attributes.push(NeighbourAttribute::LinkLayerAddress(
        router_mac.octets().to_vec(),
    ));
    msg.attributes
        .push(NeighbourAttribute::Destination(match next_hop {
            IpAddr::V4(a) => NeighbourAddress::Inet(a),
            IpAddr::V6(a) => NeighbourAddress::Inet6(a),
        }));
    msg.attributes
        .push(NeighbourAttribute::Protocol(RouteProtocol::Bgp));
    msg
}

/// Add (or replace) the FDB row on the L3 VXLAN device that maps
/// the remote PE's router MAC to the remote VTEP IP. The VXLAN
/// driver consults this to pick the right tunnel endpoint when it
/// sees the inner DMAC during encapsulation.
///
/// Unlike L2 FDB programming, an L3 VXLAN is **not** enslaved to a
/// bridge — it's a slave of a VRF master device. The FDB row
/// therefore carries only `NTF_SELF` (no `NTF_MASTER`), matching
/// what iproute2 emits for `bridge fdb add ... dev l3vxlanX self`.
///
/// # Errors
///
/// Failures classify per [`classify_apply_error`]. `EEXIST` is
/// idempotent.
pub(crate) async fn apply_add_l3vxlan_fdb(
    handle: &Handle,
    l3vxlan_ifindex: u32,
    router_mac: MacAddress,
    next_hop: IpAddr,
) -> Result<(), DataplaneError> {
    let mut req = handle
        .neighbours()
        .add_bridge(l3vxlan_ifindex, &router_mac.octets())
        .replace();
    *req.message_mut() = build_l3vxlan_fdb_message(l3vxlan_ifindex, router_mac, next_hop);
    req.execute().await.map_err(|e| classify_apply_error(&e))
}

/// Remove a previously-installed L3VXLAN FDB row.
///
/// # Errors
///
/// Failures classify per [`classify_remove_apply_error`] —
/// `ENOENT` is idempotent success so a foreign `bridge fdb del`
/// or prior partial drain doesn't wedge `L3OwnedState`.
pub(crate) async fn apply_remove_l3vxlan_fdb(
    handle: &Handle,
    l3vxlan_ifindex: u32,
    router_mac: MacAddress,
) -> Result<(), DataplaneError> {
    let mut msg = NeighbourMessage::default();
    msg.header.family = AddressFamily::Bridge;
    msg.header.ifindex = l3vxlan_ifindex;
    msg.header.kind = RouteType::Unspec;
    msg.header.flags = NeighbourFlags::Own;
    msg.attributes.push(NeighbourAttribute::LinkLayerAddress(
        router_mac.octets().to_vec(),
    ));
    match handle.neighbours().del(msg).execute().await {
        Ok(()) => Ok(()),
        Err(e) => classify_remove_apply_error(&e),
    }
}

fn build_l3vxlan_fdb_nhg_message(
    l3vxlan_ifindex: u32,
    router_mac: MacAddress,
    nh_id: u32,
) -> NeighbourMessage {
    let mut msg = NeighbourMessage::default();
    msg.header.family = AddressFamily::Bridge;
    msg.header.ifindex = l3vxlan_ifindex;
    msg.header.state = NeighbourState::Other(NUD_NOARP_PERMANENT);
    msg.header.flags = NeighbourFlags::Own | NeighbourFlags::ExtLearned;
    msg.header.kind = RouteType::Unspec;
    msg.attributes.push(NeighbourAttribute::LinkLayerAddress(
        router_mac.octets().to_vec(),
    ));
    msg.attributes
        .push(NeighbourAttribute::Other(DefaultNla::new(
            NDA_NH_ID,
            nh_id.to_ne_bytes().to_vec(),
        )));
    msg.attributes
        .push(NeighbourAttribute::Protocol(RouteProtocol::Bgp));
    msg
}

/// Install (or replace) the L3VXLAN FDB row that maps the remote
/// Router MAC to an FDB nexthop group.
///
/// # Errors
///
/// Failures classify per [`classify_apply_error`].
pub(crate) async fn apply_add_l3vxlan_fdb_nhg(
    handle: &Handle,
    l3vxlan_ifindex: u32,
    router_mac: MacAddress,
    nh_id: u32,
) -> Result<(), DataplaneError> {
    let mut req = handle
        .neighbours()
        .add_bridge(l3vxlan_ifindex, &router_mac.octets())
        .replace();
    *req.message_mut() = build_l3vxlan_fdb_nhg_message(l3vxlan_ifindex, router_mac, nh_id);
    req.execute().await.map_err(|e| classify_apply_error(&e))
}

#[cfg(test)]
mod tests {
    use super::*;
    use rustbgpd_evpn::{Ipv4Prefix, Ipv6Prefix};
    use std::net::{Ipv4Addr, Ipv6Addr};

    fn v4_prefix(addr: [u8; 4], len: u8) -> EvpnIpPrefixValue {
        EvpnIpPrefixValue::V4(Ipv4Prefix::new(Ipv4Addr::from(addr), len))
    }

    fn v6_prefix(segs: [u16; 8], len: u8) -> EvpnIpPrefixValue {
        let a = Ipv6Addr::new(
            segs[0], segs[1], segs[2], segs[3], segs[4], segs[5], segs[6], segs[7],
        );
        EvpnIpPrefixValue::V6(Ipv6Prefix::new(a, len))
    }

    #[test]
    fn build_v4_route_carries_onlink_proto_bgp_and_table() {
        let prefix = v4_prefix([198, 51, 100, 0], 24);
        let nh = IpAddr::V4(Ipv4Addr::new(10, 0, 0, 2));
        let msg = build_ip_route_message(prefix, 100, 42, nh).unwrap();
        assert_eq!(msg.header.address_family, AddressFamily::Inet);
        assert_eq!(msg.header.destination_prefix_length, 24);
        assert_eq!(msg.header.protocol, RouteProtocol::Bgp);
        assert_eq!(msg.header.scope, RouteScope::Universe);
        assert_eq!(msg.header.kind, RouteType::Unicast);
        assert!(
            msg.header.flags.contains(RouteFlags::Onlink),
            "RTNH_F_ONLINK must be set so the kernel skips the recursive lookup"
        );
        assert_eq!(msg.header.table, 100);

        let table_attr = msg.attributes.iter().find_map(|a| match a {
            RouteAttribute::Table(t) => Some(*t),
            _ => None,
        });
        assert_eq!(table_attr, Some(100));

        let dst = msg.attributes.iter().find_map(|a| match a {
            RouteAttribute::Destination(d) => Some(d.clone()),
            _ => None,
        });
        assert!(matches!(dst, Some(RouteAddress::Inet(_))));

        let gw = msg.attributes.iter().find_map(|a| match a {
            RouteAttribute::Gateway(g) => Some(g.clone()),
            _ => None,
        });
        assert!(matches!(gw, Some(RouteAddress::Inet(addr)) if addr == Ipv4Addr::new(10,0,0,2)));

        let oif = msg.attributes.iter().find_map(|a| match a {
            RouteAttribute::Oif(idx) => Some(*idx),
            _ => None,
        });
        assert_eq!(oif, Some(42));
    }

    #[test]
    fn build_v6_route_uses_inet6_family() {
        let prefix = v6_prefix([0x2001, 0xdb8, 0, 0, 0, 0, 0, 0], 64);
        let nh = IpAddr::V6(Ipv6Addr::new(0xfd00, 0, 0, 0, 0, 0, 0, 1));
        let msg = build_ip_route_message(prefix, 200, 7, nh).unwrap();
        assert_eq!(msg.header.address_family, AddressFamily::Inet6);
        assert_eq!(msg.header.destination_prefix_length, 64);
        assert!(msg.header.flags.contains(RouteFlags::Onlink));
    }

    #[test]
    fn build_route_uses_rt_table_compat_for_large_table_ids() {
        let prefix = v4_prefix([198, 51, 100, 0], 24);
        let nh = IpAddr::V4(Ipv4Addr::new(10, 0, 0, 2));
        let msg = build_ip_route_message(prefix, 50_000, 42, nh).unwrap();
        assert_eq!(msg.header.table, RT_TABLE_COMPAT);
        // The full id rides in the attribute so the kernel reads
        // the real table.
        let table_attr = msg.attributes.iter().find_map(|a| match a {
            RouteAttribute::Table(t) => Some(*t),
            _ => None,
        });
        assert_eq!(table_attr, Some(50_000));
    }

    #[test]
    fn family_mismatch_rejected_at_build_time() {
        // IPv4 prefix, IPv6 next-hop → must error rather than
        // silently miscompose. The reconciler's projection layer
        // catches this earlier; this is defense-in-depth.
        let prefix = v4_prefix([198, 51, 100, 0], 24);
        let nh = IpAddr::V6(Ipv6Addr::new(0xfd00, 0, 0, 0, 0, 0, 0, 1));
        let err = build_ip_route_message(prefix, 100, 42, nh).unwrap_err();
        assert!(matches!(err, DataplaneError::InvalidArgument(_)));
    }

    #[test]
    fn build_ecmp_route_requires_two_next_hops() {
        let prefix = v4_prefix([198, 51, 100, 0], 24);
        let nh = IpAddr::V4(Ipv4Addr::new(10, 0, 0, 2));
        let err = build_ip_route_ecmp_message(prefix, 100, 42, &[nh]).unwrap_err();
        assert!(matches!(
            err,
            DataplaneError::InvalidArgument(message)
                if message.contains("requires at least two next-hops")
        ));
    }

    #[test]
    fn build_ecmp_route_carries_onlink_marker_for_adoption() {
        let prefix = v4_prefix([198, 51, 100, 0], 24);
        let hops = [
            IpAddr::V4(Ipv4Addr::new(10, 0, 0, 2)),
            IpAddr::V4(Ipv4Addr::new(10, 0, 0, 3)),
        ];
        let msg = build_ip_route_ecmp_message(prefix, 100, 42, &hops).unwrap();
        assert_eq!(msg.header.protocol, RouteProtocol::Bgp);
        assert!(
            msg.header.flags.contains(RouteFlags::Onlink),
            "ECMP routes must carry the same RTPROT_BGP + onlink ownership marker as scalar routes",
        );
    }

    fn protocol_attr(msg: &NeighbourMessage) -> Option<RouteProtocol> {
        msg.attributes.iter().find_map(|a| match a {
            NeighbourAttribute::Protocol(p) => Some(*p),
            _ => None,
        })
    }

    #[test]
    fn build_l3_neighbor_message_carries_markers_and_ownership_stamp() {
        let nh = IpAddr::V4(Ipv4Addr::new(10, 0, 0, 2));
        let mac = MacAddress::new([0x02, 0, 0, 0, 1, 1]);
        let msg = build_l3_neighbor_message(42, nh, mac, true);
        assert_eq!(msg.header.family, AddressFamily::Inet);
        assert_eq!(msg.header.ifindex, 42);
        assert_eq!(msg.header.state, NeighbourState::Permanent);
        assert_eq!(msg.header.flags, NeighbourFlags::ExtLearned);

        let dst = msg.attributes.iter().find_map(|a| match a {
            NeighbourAttribute::Destination(NeighbourAddress::Inet(v4)) => Some(*v4),
            _ => None,
        });
        assert_eq!(dst, Some(Ipv4Addr::new(10, 0, 0, 2)));
        let lladdr = msg.attributes.iter().find_map(|a| match a {
            NeighbourAttribute::LinkLayerAddress(bytes) => Some(bytes.clone()),
            _ => None,
        });
        assert_eq!(lladdr, Some(mac.octets().to_vec()));
        // ADR-0082: the NDA_PROTOCOL ownership stamp, the same
        // RTPROT_BGP identity as our routes.
        assert_eq!(protocol_attr(&msg), Some(RouteProtocol::Bgp));
    }

    #[test]
    fn build_l3_neighbor_message_unstamped_omits_protocol() {
        // The EINVAL-retry / latched-unavailable shape (ADR-0082
        // decision 5): everything but the stamp stays identical.
        let nh = IpAddr::V6(Ipv6Addr::new(0xfd00, 0, 0, 0, 0, 0, 0, 1));
        let mac = MacAddress::new([0x02, 0, 0, 0, 1, 1]);
        let msg = build_l3_neighbor_message(42, nh, mac, false);
        assert_eq!(msg.header.family, AddressFamily::Inet6);
        assert_eq!(msg.header.flags, NeighbourFlags::ExtLearned);
        assert_eq!(protocol_attr(&msg), None);
    }

    #[test]
    fn build_l3vxlan_fdb_message_carries_bridge_shape_and_stamp() {
        let nh = IpAddr::V4(Ipv4Addr::new(10, 0, 0, 2));
        let mac = MacAddress::new([0x02, 0, 0, 0, 1, 1]);
        let msg = build_l3vxlan_fdb_message(42, mac, nh);
        assert_eq!(msg.header.family, AddressFamily::Bridge);
        assert_eq!(msg.header.ifindex, 42);
        assert_eq!(msg.header.state, NeighbourState::Other(NUD_NOARP_PERMANENT));
        assert_eq!(
            msg.header.flags,
            NeighbourFlags::Own | NeighbourFlags::ExtLearned
        );
        // AF_BRIDGE drops the stamp silently on mainline kernels —
        // it is emitted unconditionally as the forward-compatible
        // ADR-0082 posture, so the encode must always carry it.
        assert_eq!(protocol_attr(&msg), Some(RouteProtocol::Bgp));
    }
}
