frr defaults traditional
hostname member-b
log stdout informational
!
router bgp 65003
 bgp router-id 10.98.0.30
 no bgp ebgp-requires-policy
 neighbor 10.98.0.10 remote-as 65500
 neighbor 10.98.0.10 timers 10 30
 no neighbor 10.98.0.10 enforce-first-as
 neighbor 10.98.0.10 local-role rs-client
!
