frr defaults traditional
hostname member-a
log stdout informational
!
route-map lab-invalid-origin permit 10
 set as-path prepend 65099
!
router bgp 65002
 bgp router-id 10.98.0.20
 no bgp ebgp-requires-policy
 no bgp network import-check
 neighbor 10.98.0.10 remote-as 65500
 neighbor 10.98.0.10 timers 10 30
 no neighbor 10.98.0.10 enforce-first-as
 neighbor 10.98.0.10 local-role rs-client
 address-family ipv4 unicast
  network 198.51.100.0/24
 exit-address-family
!
