#!/usr/bin/env bash
# ADR-0113 outbound prefix-limit integration receipt driver.
#
# Fixed shape, no arguments. Starts a real rustbgpd, runs four real BGP stub
# sessions against it through the real encoder, and gates on the wire-side
# prefix counts plus the operator-visible surfaces. This is a behavior
# receipt, not a timing one: it deliberately has no host-quiescence preflight
# and publishes no performance number.
#
# Backs docs/perf/outbound-prefix-limits-2026-07.md.

set -euo pipefail

readonly BGP_PORT=17900
readonly METRICS_PORT=19179
readonly DAEMON_START_TIMEOUT=60

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd -- "${here}/../../.." && pwd)"
readonly here REPO
readonly OUT="${REPO}/target/outbound-prefix-limits"
# The gRPC UDS path has to fit `sockaddr_un.sun_path`, which a checkout under
# a deep path does not. Keep the runtime state (socket included) on a short
# private path and leave the receipt artifacts under target/.
readonly RUNDIR="/tmp/rustbgpd-oprefix-$$"

fail() {
    echo "run-receipt: $*" >&2
    exit 1
}

# --- provenance --------------------------------------------------------------
cd "${REPO}"
commit="$(git rev-parse HEAD)"
if [ -n "$(git status --porcelain)" ]; then
    fail "working tree is dirty; run this from the immutable commit to measure"
fi

rm -rf "${OUT}" "${RUNDIR}"
mkdir -p "${OUT}" "${RUNDIR}"
{
    echo "commit ${commit}"
    echo "tree $(git rev-parse "HEAD^{tree}")"
    echo "rustc $(rustc --version)"
    echo "started $(date -u +%Y-%m-%dT%H:%M:%SZ)"
} >"${OUT}/provenance.txt"

# --- build -------------------------------------------------------------------
cargo build --release --locked -p rustbgpd -p rustbgpctl >"${OUT}/build-daemon.log" 2>&1 \
    || fail "daemon/CLI build failed (see ${OUT}/build-daemon.log)"
(cd "${here}" && cargo build --release --locked) >"${OUT}/build-harness.log" 2>&1 \
    || fail "harness build failed (see ${OUT}/build-harness.log)"

readonly DAEMON="${REPO}/target/release/rustbgpd"
readonly RBGP="${REPO}/target/release/rbgp"
readonly HARNESS="${here}/target/release/outboundlimits"
sha256sum "${DAEMON}" "${RBGP}" "${HARNESS}" | sed "s#${REPO}/##; s#${here}/##" \
    >"${OUT}/binaries.sha256"

# --- scenario ----------------------------------------------------------------
# One config body, three limit generations. The starting generation caps below
# what the source announces; `lower` asks for less than current usage and must
# be rejected whole; `raise` opens exactly enough capacity for the full table.
emit_config() {
    local path="$1" v4="$2" v6="$3"
    cat >"${path}" <<EOF
# Generated by bench/scale/outbound-prefix-limits/run-receipt.sh — do not edit.
[global]
asn = 65500
router_id = "10.255.0.1"
listen_port = ${BGP_PORT}
runtime_state_dir = "${RUNDIR}"

[global.telemetry]
prometheus_addr = "127.0.0.1:${METRICS_PORT}"
log_format = "json"

[global.telemetry.grpc_uds]
path = "${RUNDIR}/grpc.sock"
principal = "operator"

[security.grpc]
enforcement = "tier"

[security.grpc.roles]
operator = "operator"

# The capped member inherits both maxima from its peer group and sets none of
# its own: ADR-0113's inheritance path, not a neighbor-level shortcut.
[peer_groups.capped-clients]
hold_time = 180
families = ["ipv4_unicast", "ipv6_unicast"]
# These sessions run over IPv4 transport, so an eBGP IPv6 export has no
# derivable next hop without this. Unrelated to ADR-0113, but without it the
# IPv6 half of the receipt would silently measure nothing.
local_ipv6_nexthop = "2001:db8:ffff::ffff"
max_prefixes_out_ipv4 = ${v4}
max_prefixes_out_ipv6 = ${v6}

# Same staging profile, no maxima: this group's member must land in the same
# update group as the capped one.
[peer_groups.open-clients]
hold_time = 180
families = ["ipv4_unicast", "ipv6_unicast"]
local_ipv6_nexthop = "2001:db8:ffff::ffff"

[[neighbors]]
address = "127.9.0.1"
remote_asn = 64601
description = "route-source"
hold_time = 180
families = ["ipv4_unicast", "ipv6_unicast"]

[[neighbors]]
address = "127.9.0.2"
remote_asn = 64602
description = "grouped-capped-member"
peer_group = "capped-clients"

[[neighbors]]
address = "127.9.0.3"
remote_asn = 64603
description = "grouped-unlimited-sibling"
peer_group = "open-clients"

# RFC 7947 per-client best-path puts this peer on the private per-peer
# distribution path, so the same maxima are exercised off the shared fanout.
[[neighbors]]
address = "127.9.0.4"
remote_asn = 64604
description = "private-capped-peer"
hold_time = 180
families = ["ipv4_unicast", "ipv6_unicast"]
route_server_client = true
per_client_best = true
max_prefixes_out_ipv4 = ${v4}
max_prefixes_out_ipv6 = ${v6}
EOF
}

emit_config "${OUT}/config.toml" 8 4
emit_config "${OUT}/config.lower.toml" 2 1
emit_config "${OUT}/config.raise.toml" 12 6

for generation in config config.lower config.raise; do
    "${DAEMON}" --check "${OUT}/${generation}.toml" >"${OUT}/check-${generation}.log" 2>&1 \
        || fail "generated ${generation}.toml failed rustbgpd --check"
done

# --- daemon ------------------------------------------------------------------
daemon_pid=""
cleanup() {
    if [ -n "${daemon_pid}" ] && kill -0 "${daemon_pid}" 2>/dev/null; then
        kill "${daemon_pid}" 2>/dev/null || true
        wait "${daemon_pid}" 2>/dev/null || true
    fi
    rm -rf "${RUNDIR}"
}
trap cleanup EXIT

RUST_LOG=info "${DAEMON}" "${OUT}/config.toml" >"${OUT}/daemon.log" 2>&1 &
daemon_pid=$!

deadline=$((SECONDS + DAEMON_START_TIMEOUT))
until [ -S "${RUNDIR}/grpc.sock" ] && "${RBGP}" --addr "unix://${RUNDIR}/grpc.sock" \
        global >/dev/null 2>&1; do
    kill -0 "${daemon_pid}" 2>/dev/null || fail "daemon exited during startup (see ${OUT}/daemon.log)"
    [ "${SECONDS}" -lt "${deadline}" ] || fail "daemon did not become ready in ${DAEMON_START_TIMEOUT}s"
    sleep 0.2
done

# --- measured run ------------------------------------------------------------
harness_status=0
"${HARNESS}" \
    "${BGP_PORT}" \
    "${daemon_pid}" \
    "${RBGP}" \
    "unix://${RUNDIR}/grpc.sock" \
    "127.0.0.1:${METRICS_PORT}" \
    "${OUT}/config.toml" \
    "${OUT}/config.lower.toml" \
    "${OUT}/config.raise.toml" \
    "${OUT}" >"${OUT}/harness.log" 2>&1 || harness_status=$?
cat "${OUT}/harness.log"

# --- bounded log-episode gates ----------------------------------------------
# ADR-0113's episode contract is a log surface, so it is gated here rather
# than in the harness: exactly one open, exactly one recovery, per family.
log_status=0
log_check() {
    local name="$1" want="$2" pattern="$3"
    local got
    got="$(grep -c -- "${pattern}" "${OUT}/daemon.log" || true)"
    if [ "${got}" -eq "${want}" ]; then
        echo "CHECK ${name} PASS got=${got} want=${want}"
    else
        echo "CHECK ${name} FAIL got=${got} want=${want}"
        log_status=1
    fi
}

# Two limited peers x two families, one warning each, and no per-prefix spam.
log_check log.episode_opened 4 "outbound prefix limit reached"
log_check log.episode_recovered 4 "outbound prefix limit recovered"
log_check log.lowering_rejected 1 "SIGHUP reload rejected"
log_check log.rejection_names_the_violation 1 "above the requested maximum"
# ADR-0113: "Limit edits are live, local RIB-manager changes. They do not
# reset the session." Neither SIGHUP in this run changes anything but the two
# maxima, so no peer may be torn down and re-created.
log_check log.no_peer_rebuild_on_limit_edit 0 '"message":"peer deleted"'

cleanup
daemon_pid=""

{
    echo "finished $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "harness_exit ${harness_status}"
    echo "log_gate_exit ${log_status}"
} >>"${OUT}/provenance.txt"
(cd "${OUT}" && sha256sum ./*.json ./*.prom ./*.txt ./*.toml >checksums.sha256)

if [ "${harness_status}" -ne 0 ] || [ "${log_status}" -ne 0 ]; then
    echo "RECEIPT FAIL (harness=${harness_status} log=${log_status}); raw output in ${OUT}" >&2
    exit 1
fi
echo "RECEIPT PASS; raw output in ${OUT}"
