frr version 10.7.1
frr defaults traditional
log stdout informational
!
ip route 198.51.100.0/24 Null0
ip route 203.0.113.0/24 Null0
!
router bgp 65002
 bgp router-id 10.96.0.20
 no bgp ebgp-requires-policy
 neighbor 10.96.0.10 remote-as 65001
 !
 address-family ipv4 unicast
  network 198.51.100.0/24
 exit-address-family
!
