#!/usr/bin/env python3
"""Generate the OpenBGPD 9.1 cell of the IXP receipt matrix (LAN-334).

Mirrors gen-scenario.py's addressing contract EXACTLY (see `stub_addr`,
`stub_asn`, `base_prefix` in src/main.rs): the reloadstall harness stub `i`
binds source 127.1.(i//200).(i%200+1) with ASN 64512+i, dials
127.0.0.1:<port>, and announces /24s from 20.0.0.0 with synthetic NEXT_HOP
10.9.x.y. This emits an OpenBGPD route server: `transparent-as yes` (no AS
prepend), `set nexthop no-modify` on export, `fib-update no`.

The generation-varying filter rules live in an included rule file, so a
reload is exactly the harness's contract: copy gen-a.conf/gen-b.conf over
gen.conf, then `bgpctl reload` (the harness reload_cmd). Like
gen-scenario.py's historical mode, each generation carries a flat two-term
ruleset: a content-real but output-neutral import reject (an out-of-table
prefix that changes between generations) and a match rule tagging the
generation community 65400:1000 / 65400:2000 on export.

NEXT_HOP qualification: bgpd validates next hops against the kernel FIB even
with `fib-update no` (see tests/interop/configs/bgpd-m86-c1.conf, where the
clab topology installs static kernel glue routes). The matrix host cannot
install kernel routes per cell, so this config uses `nexthop qualify via
default` instead: the synthetic 10.9.x.y next hops qualify via the host's
default route. The host (shared via --network=host) MUST have a default
route or every route stays ineligible.

Usage:
    gen-obgpd-scenario.py <n_peers> <out_dir> [listen_port] [conf_dir]

conf_dir: directory where the RUNNING bgpd sees these files (include paths
are absolute; default /etc/bgpd — i.e. `docker run -v <out_dir>:/etc/bgpd`).

Emits into <out_dir>: bgpd.conf, gen.conf (live, starts as gen-a),
gen-a.conf, gen-b.conf.
"""
import pathlib
import sys

if len(sys.argv) < 3:
    sys.exit(__doc__)

n_peers = int(sys.argv[1])
out = pathlib.Path(sys.argv[2])
port = int(sys.argv[3]) if len(sys.argv) > 3 else 1790
conf_dir = sys.argv[4] if len(sys.argv) > 4 else "/etc/bgpd"
out.mkdir(parents=True, exist_ok=True)

GLOBAL_ASN = 65500  # not in 64512..64512+n_peers, so every neighbor is eBGP


def stub_addr(i: int) -> str:
    return f"127.1.{i // 200}.{i % 200 + 1}"


def stub_asn(i: int) -> int:
    return 64512 + i


GENERATIONS = [
    ("gen-a.conf", "192.0.2.0/24", "65400:1000"),
    ("gen-b.conf", "198.51.100.0/24", "65400:2000"),
]

for fname, reject_prefix, community in GENERATIONS:
    (out / fname).write_text(
        f"""# IXP-matrix policy generation - generated by gen-obgpd-scenario.py.
# Flat two-term generation ruleset, included after the base allow rules
# (last matching rule wins). The deny is content-real but output-neutral
# ({reject_prefix} is outside the announced 20.0.0.0-26.x base table); the
# match tags every advertised route with the generation community, which the
# harness tracks to timestamp reload completion.
deny from any prefix {reject_prefix}
match to any set community {community}
"""
    )

# The live include starts as generation A; the harness copies gen-a/gen-b
# over it before each `bgpctl reload`.
(out / "gen.conf").write_text((out / "gen-a.conf").read_text())

config = [
    "# IXP-matrix OpenBGPD 9.1 route server - generated by gen-obgpd-scenario.py.",
    "# Run: docker run -d --network=host -v <out_dir>:/etc/bgpd openbgpd/openbgpd:9.1",
    "# Reload: overwrite gen.conf, then `bgpctl reload`.",
    "",
    f"AS {GLOBAL_ASN}",
    "router-id 10.0.0.1",
    "fib-update no",
    "transparent-as yes",
    f"listen on 127.0.0.1 port {port}",
    "",
    "# bgpd validates next hops against the kernel FIB even with fib-update",
    "# no; the stubs' synthetic 10.9.x.y next hops exist nowhere, so qualify",
    "# them via the host's default route (no kernel glue routes needed).",
    "nexthop qualify via default",
    "",
]
for i in range(n_peers):
    config += [
        f"neighbor {stub_addr(i)} {{",
        f'\tdescr "stub{i}"',
        f"\tremote-as {stub_asn(i)}",
        "\tpassive",  # stubs always dial in; no outbound race to stub port 179
        "\tholdtime 180",
        "\tannounce IPv4 unicast",
        "}",
    ]
config += [
    "",
    "# Route-server base ruleset; the generation-varying reject + community",
    "# terms are included last so they win last-match evaluation.",
    "allow from any",
    "allow to any set nexthop no-modify",
    f'include "{conf_dir}/gen.conf"',
    "",
]
(out / "bgpd.conf").write_text("\n".join(config))

print(
    f"wrote {out.resolve()}/bgpd.conf ({n_peers} neighbors), gen.conf, "
    f"gen-a.conf, gen-b.conf; listen 127.0.0.1:{port}, include dir {conf_dir}"
)
