#!/usr/bin/env python3
"""Generate the BIRD 3.3.1 cell of the IXP receipt matrix (LAN-334).

Mirrors gen-scenario.py's addressing contract EXACTLY (see `stub_addr`,
`stub_asn`, `base_prefix` in src/main.rs): the reloadstall harness stub `i`
binds source 127.1.(i//200).(i%200+1) with ASN 64512+i, dials
127.0.0.1:<port>, and announces /24s from 20.0.0.0 with synthetic NEXT_HOP
10.9.x.y. This emits a BIRD route server with N eBGP `rs client` neighbors
(transparent: no AS prepend, `next hop keep`).

The generation-varying policy lives in included filter files, so a reload is
exactly the harness's contract: copy gen-a.conf/gen-b.conf over gen.conf,
then `birdc configure` (the harness reload_cmd). Like gen-scenario.py's
historical mode, the import filter carries a content-real but output-neutral
reject term (an out-of-table prefix that changes between generations) and
the export filter tags the generation community 65500:1000 / 65500:2000.

NEXT_HOP glue (the classic bgperf BIRD gotcha): 10.9.x.y exists nowhere, so
without help BIRD marks every route unreachable and exports nothing. The
static protocol below covers 10.9.0.0/16 with a device route and every
session resolves next hops through it via `gateway recursive`.

Usage:
    gen-bird-scenario.py <n_peers> <out_dir> [listen_port] [threads] [conf_dir]

threads: BIRD 3 `threads` knob (default 8).
conf_dir: directory where the RUNNING bird sees these files (include paths
are absolute; default /etc/bird — i.e. `docker run -v <out_dir>:/etc/bird`).

Emits into <out_dir>: bird.conf, gen.conf (live, starts as gen-a),
gen-a.conf, gen-b.conf.
"""
import pathlib
import sys

if len(sys.argv) < 3:
    sys.exit(__doc__)

n_peers = int(sys.argv[1])
out = pathlib.Path(sys.argv[2])
port = int(sys.argv[3]) if len(sys.argv) > 3 else 1790
threads = int(sys.argv[4]) if len(sys.argv) > 4 else 8
conf_dir = sys.argv[5] if len(sys.argv) > 5 else "/etc/bird"
out.mkdir(parents=True, exist_ok=True)

GLOBAL_ASN = 65500  # not in 64512..64512+n_peers, so every neighbor is eBGP


def stub_addr(i: int) -> str:
    return f"127.1.{i // 200}.{i % 200 + 1}"


def stub_asn(i: int) -> int:
    return 64512 + i


# (filename, import-reject prefix, export community) — same generation
# semantics as gen-scenario.py historical mode: the reject prefix is out of
# the announced 20.0.0.0-26.x base table, so the import change is
# content-real but output-neutral.
GENERATIONS = [
    ("gen-a.conf", "192.0.2.0/24", "(65500, 1000)"),
    ("gen-b.conf", "198.51.100.0/24", "(65500, 2000)"),
]

for fname, reject_prefix, community in GENERATIONS:
    (out / fname).write_text(
        f"""# IXP-matrix policy generation - generated by gen-bird-scenario.py.
# member_in rejects one out-of-table prefix ({reject_prefix}): content-real,
# output-neutral. member_out tags every advertised route with the generation
# community; the harness tracks it to timestamp reload completion.
filter member_in {{
    if net = {reject_prefix} then reject;
    accept;
}}

filter member_out {{
    bgp_community.add({community});
    accept;
}}
"""
    )

# The live include starts as generation A; the harness copies gen-a/gen-b
# over it before each `birdc configure`.
(out / "gen.conf").write_text((out / "gen-a.conf").read_text())

config = [
    "# IXP-matrix BIRD 3.3.1 route server - generated by gen-bird-scenario.py.",
    "# Run: docker run -d --network=host -v <out_dir>:/etc/bird <bird-image> \\",
    "#          bird -f -c /etc/bird/bird.conf",
    "# Reload: overwrite gen.conf, then `birdc configure`.",
    "",
    "router id 10.0.0.1;",
    f"threads {threads};",
    "log stderr all;",
    "",
    "protocol device { scan time 10; }",
    "",
    "# NEXT_HOP glue: device routes over lo so the stubs' synthetic",
    "# 10.9.x.y next hops (and, with multihop, the 127.1.x.y neighbor",
    "# addresses) resolve; sessions use `gateway recursive` below.",
    "protocol static nh_glue {",
    "    ipv4;",
    '    route 10.9.0.0/16 via "lo";',
    '    route 127.1.0.0/16 via "lo";',
    "}",
    "",
    f'include "{conf_dir}/gen.conf";',
    "",
    "template bgp rs_member {",
    f"    local 127.0.0.1 port {port} as {GLOBAL_ASN};",
    "    rs client;",
    "    passive;",  # stubs always dial in; no outbound race to stub port 179
    "    multihop;",  # loopback peering, no shared non-lo subnet
    "    hold time 180;",
    "    ipv4 {",
    "        import filter member_in;",
    "        export filter member_out;",
    "        next hop keep;",
    "        gateway recursive;",
    "    };",
    "}",
    "",
]
for i in range(n_peers):
    config.append(
        f"protocol bgp peer{i} from rs_member {{ "
        f"neighbor {stub_addr(i)} as {stub_asn(i)}; }}"
    )
config.append("")
(out / "bird.conf").write_text("\n".join(config))

print(
    f"wrote {out.resolve()}/bird.conf ({n_peers} neighbors, threads={threads}), "
    f"gen.conf, gen-a.conf, gen-b.conf; listen 127.0.0.1:{port}, "
    f"include dir {conf_dir}"
)
