#!/usr/bin/env python3
"""Generate the daemon-side scenario the reloadstall harness drives.

The harness (`src/main.rs`) is only the client side: N real BGP stub
sessions that dial a *running* rustbgpd route server. This script emits the
route server it dials — a config with N route-server-client neighbors and
the two `.rpol` policy generations the harness alternates on each SIGHUP —
so the receipt in `docs/perf/reload-stall-2026-07.md` reproduces from the
repo alone.

Addressing MUST match `src/main.rs`: stub `i` binds source
`127.1.(i//200).(i%200+1)` (`stub_addr`) with ASN `64512+i` (`stub_asn`)
and BGP-id `240.1.x.y` (higher than the daemon's router-id, so the inbound
connection wins RFC 4271 §6.8 collision resolution against the daemon's
active dial to the unreachable stub port 179). The base table lives in
`20.0.0.0 .. 26.x` (`base_prefix`), so the two import-chain reject prefixes
(`192.0.2.0/24` / `198.51.100.0/24`) are out-of-table: the import change is
content-real (chain reinstalled, Route Refresh fires) but output-neutral, so
the re-advertisement wire volume stays attributable to the export swap alone.

Both generations define the SAME policy names (`member-in` / `member-out`)
with different bodies. Only one file is ever loaded at a time (copied over
the live file per reload), so there is no shared-namespace collision; the
TOML `import_chain` / `export_chain` name references stay valid across swaps.

Usage:
    gen-scenario.py <n_peers> <out_dir> [listen_port]

Emits into <out_dir>: config.toml, member.rpol (live, starts as gen-a),
gen-a.rpol (community 65500:1000), gen-b.rpol (community 65500:2000).
Receipt shape: n_peers=700, total_prefixes=400400 (harness arg), port 1790.
"""
import pathlib
import sys

if len(sys.argv) < 3:
    sys.exit(__doc__)

n_peers = int(sys.argv[1])
out = pathlib.Path(sys.argv[2])
port = int(sys.argv[3]) if len(sys.argv) > 3 else 1790
out.mkdir(parents=True, exist_ok=True)
rundir = out.resolve()

# The gRPC UDS path lives under rundir and is bound with bind(2), which caps
# sun_path at ~108 bytes (SUN_LEN). A long out_dir (e.g. a deep scratchpad)
# makes the daemon fail to bind and shut down; fail here instead. Keep out_dir
# short, e.g. /tmp/rls/full.
sock = f"{rundir}/grpc.sock"
if len(sock.encode()) > 100:
    sys.exit(f"grpc.sock path too long for SUN_LEN ({len(sock)} bytes): {sock}\n"
             f"pass a shorter <out_dir> (e.g. /tmp/rls/full).")

GLOBAL_ASN = 65500  # not in 64512..64512+n_peers, so every neighbor is eBGP


def stub_addr(i: int) -> str:
    return f"127.1.{i // 200}.{i % 200 + 1}"


def stub_asn(i: int) -> int:
    return 64512 + i


# (filename, import-reject prefix, export community) per generation.
GENERATIONS = [
    ("gen-a.rpol", "192.0.2.0/24", "65500:1000"),
    ("gen-b.rpol", "198.51.100.0/24", "65500:2000"),
]

for fname, reject_prefix, community in GENERATIONS:
    (out / fname).write_text(
        f"""# reload-stall policy generation - generated by gen-scenario.py.
#
# member-in rejects one out-of-table prefix ({reject_prefix} is outside the
# announced 20.0.0.0-26.x base table), so the import chain is content-real:
# reinstalled per peer, 700 Route Refreshes fire, 400k routes re-enter the
# new chain, but output-neutral - no announced route's verdict changes.
# member-out tags every advertised route with the generation community the
# harness samples to confirm which generation is live at the receiver.
policy member-in {{
    term drop-blocked {{ if route.prefix == {reject_prefix} {{ reject }} }}
    term default {{ accept }}
}}

policy member-out {{
    term tag {{ add community {community}; accept }}
}}
"""
    )

# The live file starts as generation A; the harness copies gen-a/gen-b over it.
(out / "member.rpol").write_text((out / "gen-a.rpol").read_text())

config = [
    "# reload-stall route-server scenario — generated by gen-scenario.py.",
    "# Stock daemon config: worker_threads unset => min(CPU, 8), matching the",
    "# receipt. Start load-gated (1-min loadavg < 2.0), --release.",
    "",
    "[global]",
    f"asn = {GLOBAL_ASN}",
    'router_id = "10.0.0.1"',  # < 240.1.x.y so the stubs win collision resolution
    f"listen_port = {port}",
    f'runtime_state_dir = "{rundir}"',
    "",
    "[global.telemetry]",
    'log_format = "json"',  # reload wall time comes from the JSON "config reload complete" line
    "",
    "[global.telemetry.grpc_uds]",
    f'path = "{rundir}/grpc.sock"',  # the `rbgp health` control-query probe dials this
    "",
    "[security.grpc]",
    # Loopback benchmark: UDS access is gated by file perms; legacy mode lets
    # the control-query probe dial without a per-method role map.
    'enforcement = "legacy"',
    "",
    "[policy]",
    'rpol_files = ["member.rpol"]',
    'import_chain = ["member-in"]',
    'export_chain = ["member-out"]',
    "",
]
for i in range(n_peers):
    config += [
        "[[neighbors]]",
        f'address = "{stub_addr(i)}"',
        f"remote_asn = {stub_asn(i)}",
        "route_server_client = true",
        'families = ["ipv4_unicast"]',
        "hold_time = 180",
        "",
    ]
(out / "config.toml").write_text("\n".join(config))

print(
    f"wrote {rundir}/config.toml ({n_peers} neighbors), member.rpol, "
    f"gen-a.rpol, gen-b.rpol; listen_port={port}, grpc_uds={rundir}/grpc.sock"
)
