[package]
name = "rustbgpd-policy-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.rustbgpd-policy]
path = ".."

[[bin]]
name = "rpol_compile"
path = "fuzz_targets/rpol_compile.rs"
test = false
doc = false

[workspace]

[[bin]]
name = "dataset_parse"
path = "fuzz_targets/dataset_parse.rs"
test = false
doc = false
