Building configuration...

Current configuration:
!
frr version 10.7.1_git
frr defaults traditional
hostname frr
log stdout informational
!
vrf vrf111
exit-vrf
!
router bgp 65001
 bgp router-id 10.111.0.2
 no bgp default ipv4-unicast
 neighbor 2001:db8:111:10::1 remote-as 65001
 neighbor 2001:db8:111:10::1 passive
 neighbor 2001:db8:111:10::1 update-source 2001:db8:111:10::2
 neighbor 2001:db8:111:10::1 timers 3 90
 neighbor 2001:db8:111:10::1 timers connect 1
 neighbor 2001:db8:111:10::1 capability extended-nexthop
 !
 segment-routing srv6
  locator srv6-proof
 exit
 !
 address-family ipv4 vpn
  neighbor 2001:db8:111:10::1 activate
 exit-address-family
 !
 address-family ipv6 vpn
  neighbor 2001:db8:111:10::1 activate
 exit-address-family
exit
!
router bgp 65001 vrf vrf111
 bgp router-id 10.111.0.2
 !
 address-family ipv4 unicast
  sid vpn export auto
  rd vpn export 65001:111
  rt vpn export 65001:111
  export vpn
 exit-address-family
 !
 address-family ipv6 unicast
  sid vpn export auto
  rd vpn export 65001:111
  rt vpn export 65001:111
  export vpn
 exit-address-family
exit
!
segment-routing
 srv6
  locators
   locator srv6-proof
    prefix 2001:db8:111:1::/64
   exit
   !
  exit
  !
 exit
 !
exit
!
end
