#!/usr/bin/env bash
# Config persistence / history / rollback / commit-confirm integration receipt.
#
# Fixed shape, no arguments. Deploys the config the way the quick-start now
# does — a template copied into the daemon's writable state volume — then runs
# three real BGP stub sessions against a real rustbgpd through the real
# encoder while the harness drives persisted mutations, history, rollback,
# commit-confirm (including a SIGKILL inside the confirmation window), and an
# injected persistence failure.
#
# This is a behavior receipt, not a timing one: it deliberately has no
# host-quiescence preflight and publishes no performance number.
#
# Backs docs/perf/config-persistence-2026-07.md.

set -euo pipefail

readonly BGP_PORT=17910
readonly METRICS_PORT=19189

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd -- "${here}/../../.." && pwd)"
readonly here REPO
readonly OUT="${REPO}/target/config-persistence"
# The gRPC UDS path has to fit `sockaddr_un.sun_path`, which a checkout under a
# deep path does not. Keep the deployment on a short private path and leave the
# receipt artifacts under target/.
readonly RUNDIR="/tmp/rustbgpd-cfgpersist-$$"
readonly CONFDIR="${RUNDIR}/etc"
readonly STATEDIR="${RUNDIR}/state"

fail() {
    echo "run-receipt: $*" >&2
    exit 1
}

# The rejected-persistence phase injects its failure by sealing the config
# directory to 0o500. uid 0 ignores mode bits, so the whole phase would be
# vacuous.
[ "$(id -u)" -ne 0 ] || fail "refusing to run as root: the injected persistence failure cannot bind"

# The daemon binds its BGP listen port without SO_REUSEADDR, so a socket left
# on it by an earlier run — a live listener or a lingering FIN_WAIT/TIME_WAIT
# entry — makes the very first generation come up unable to accept sessions.
# Refuse rather than publish a run whose baseline could not establish.
if command -v ss >/dev/null 2>&1; then
    if ss -tanH 2>/dev/null | grep -qE "[:.]${BGP_PORT}([^0-9]|$)"; then
        fail "TCP ${BGP_PORT} is still held (listener or TIME_WAIT); wait for it to drain"
    fi
fi

# --- provenance --------------------------------------------------------------
cd "${REPO}"
commit="$(git rev-parse HEAD)"
if [ -n "$(git status --porcelain)" ]; then
    fail "working tree is dirty; run this from the immutable commit to measure"
fi

rm -rf "${OUT}" "${RUNDIR}"
mkdir -p "${OUT}"
mkdir -m 0700 -- "${RUNDIR}"
mkdir -p "${CONFDIR}"
mkdir -m 0700 -- "${STATEDIR}"
{
    echo "commit ${commit}"
    echo "tree $(git rev-parse "HEAD^{tree}")"
    echo "rustc $(rustc --version)"
    echo "started $(date -u +%Y-%m-%dT%H:%M:%SZ)"
} >"${OUT}/provenance.txt"

# --- build -------------------------------------------------------------------
cargo build --release --locked -p rustbgpd -p rustbgpctl >"${OUT}/build-daemon.log" 2>&1 \
    || fail "daemon/CLI build failed (see ${OUT}/build-daemon.log)"
(cd "${here}" && cargo build --release --locked) >"${OUT}/build-harness.log" 2>&1 \
    || fail "harness build failed (see ${OUT}/build-harness.log)"

readonly DAEMON="${REPO}/target/release/rustbgpd"
readonly RBGP="${REPO}/target/release/rbgp"
readonly HARNESS="${here}/target/release/configpersist"
sha256sum "${DAEMON}" "${RBGP}" "${HARNESS}" | sed "s#${REPO}/##; s#${here}/##" \
    >"${OUT}/binaries.sha256"

# --- deployment --------------------------------------------------------------
# The shipped config is a TEMPLATE. Persistence writes a temp file alongside
# the config and renames it, so the directory the daemon reads from must be
# writable — the template is copied into the daemon's own writable state
# volume, exactly as the quick-start and the container images now do.
cat >"${OUT}/config.template.toml" <<EOF
# Generated by bench/scale/config-persistence/run-receipt.sh — do not edit.
[global]
asn = 65500
router_id = "10.255.0.2"
listen_port = ${BGP_PORT}
runtime_state_dir = "${STATEDIR}"

[global.telemetry]
prometheus_addr = "127.0.0.1:${METRICS_PORT}"
log_format = "json"

[global.telemetry.grpc_uds]
path = "${STATEDIR}/grpc.sock"
principal = "operator"

[security.grpc]
enforcement = "tier"

[security.grpc.roles]
operator = "operator"

[[neighbors]]
address = "127.9.2.1"
remote_asn = 64701
description = "route-source"
hold_time = 180
families = ["ipv4_unicast", "ipv6_unicast"]
# These sessions run over IPv4 transport, so an eBGP IPv6 export has no
# derivable next hop without this. Unrelated to config persistence, but
# without it the IPv6 half of the wire evidence would be silently empty.
local_ipv6_nexthop = "2001:db9:ffff::ffff"

[[neighbors]]
address = "127.9.2.2"
remote_asn = 64702
description = "subject"
hold_time = 180
families = ["ipv4_unicast", "ipv6_unicast"]
local_ipv6_nexthop = "2001:db9:ffff::ffff"

[[neighbors]]
address = "127.9.2.3"
remote_asn = 64703
description = "bystander"
hold_time = 180
families = ["ipv4_unicast", "ipv6_unicast"]
local_ipv6_nexthop = "2001:db9:ffff::ffff"
EOF

install -m 0644 "${OUT}/config.template.toml" "${CONFDIR}/config.toml"
"${DAEMON}" --check "${CONFDIR}/config.toml" >"${OUT}/check-template.log" 2>&1 \
    || fail "the deployed config failed rustbgpd --check"

cleanup() {
    # The harness seals the config directory on purpose; never leave it that
    # way, or the cleanup below cannot remove it.
    chmod 0700 "${CONFDIR}" 2>/dev/null || true
    pkill -x -f "${DAEMON} ${CONFDIR}/config.toml" 2>/dev/null || true
    rm -rf "${RUNDIR}"
}
trap cleanup EXIT

# --- measured run ------------------------------------------------------------
# The harness owns the daemon lifecycle: three of the five areas it covers only
# exist across a restart.
harness_status=0
"${HARNESS}" \
    "${DAEMON}" \
    "${RBGP}" \
    "${CONFDIR}/config.toml" \
    "${STATEDIR}" \
    "${BGP_PORT}" \
    "127.0.0.1:${METRICS_PORT}" \
    "${OUT}" >"${OUT}/harness.log" 2>&1 || harness_status=$?
cat "${OUT}/harness.log"

# --- bounded log-episode gates ----------------------------------------------
# The boot-revert banner and the absence of a session teardown are log
# surfaces the harness cannot see, so they are gated here.
cat "${OUT}"/daemon-*.log >"${OUT}/daemon-all.log" 2>/dev/null || true
# The rejected-mutation phase runs in the last daemon generation.
mapfile -t generations < <(printf '%s\n' "${OUT}"/daemon-*.log | sort -V)
cp "${generations[${#generations[@]} - 1]}" "${OUT}/daemon-last.log"

log_status=0
log_check() {
    local name="$1" want="$2" file="$3" pattern="$4"
    local got
    got="$(grep -c -- "${pattern}" "${file}" || true)"
    if [ "${got}" -eq "${want}" ]; then
        echo "CHECK ${name} PASS got=${got} want=${want}"
    else
        echo "CHECK ${name} FAIL got=${got} want=${want}"
        log_status=1
    fi
}

# Exactly one boot revert across the whole run: the SIGKILL inside the
# confirmation window. The clean SIGTERM restart must not produce one.
log_check log.boot_revert_notice 1 "${OUT}/daemon-all.log" "commit-confirm boot revert"
# The confirm id alone also appears on the apply audit line and on the
# structured revert record, so the gate matches the operator banner that has to
# name the transaction it undid.
log_check log.boot_revert_names_the_transaction 1 "${OUT}/daemon-all.log" \
    'commit-confirm boot revert: transaction "receipt-killed"'
# A rejected mutation must not tear the subject's session down. `peer deleted`
# is the daemon's own teardown line; the subject address must never appear on
# one in the generation that runs the rejection phase.
log_check log.subject_peer_never_deleted 0 "${OUT}/daemon-last.log" '"message":"peer deleted","peer":"127.9.2.2"'
log_check log.no_panics 0 "${OUT}/daemon-all.log" "panicked at"

cleanup
trap - EXIT

{
    echo "finished $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "harness_exit ${harness_status}"
    echo "log_gate_exit ${log_status}"
} >>"${OUT}/provenance.txt"
(cd "${OUT}" && sha256sum ./*.json ./*.prom ./*.txt ./*.toml >checksums.sha256)

if [ "${harness_status}" -ne 0 ] || [ "${log_status}" -ne 0 ]; then
    echo "RECEIPT FAIL (harness=${harness_status} log=${log_status}); raw output in ${OUT}" >&2
    exit 1
fi
echo "RECEIPT PASS; raw output in ${OUT}"
