[package]
name = "rrtransport"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1"
rustbgpd-evpn-load = { path = "../../evpn-load" }
rustbgpd-fsm.workspace = true
rustbgpd-policy.workspace = true
rustbgpd-rib.workspace = true
rustbgpd-telemetry = { workspace = true, features = ["jemalloc"] }
rustbgpd-transport = { workspace = true, features = ["bench-internals"] }
rustbgpd-wire.workspace = true
tikv-jemallocator.workspace = true
tokio.workspace = true
