frr defaults traditional
hostname client-a
log stdout informational
!
router bgp 65001
 bgp router-id 10.97.0.20
 no bgp network import-check
 neighbor 10.97.0.1 remote-as 65001
 neighbor 10.97.0.1 timers 10 30
 address-family ipv4 unicast
  network 198.51.100.0/24
 exit-address-family
!
