frr defaults traditional
hostname client-b
log stdout informational
!
router bgp 65001
 bgp router-id 10.97.0.10
 no bgp network import-check
 neighbor 10.97.0.1 remote-as 65001
 neighbor 10.97.0.1 timers 10 30
!
