#!/usr/bin/env python3
"""Drive a running rustbgpd the way a containerized controller would.

Checks health, watches the live event stream while injecting and withdrawing
one route, and prints the events that mutation produced. GetHealth and
WatchEvents are `sensitive_read`; AddPath and DeletePath are `operator_only`,
so this script needs a principal mapped to the Operator role.

Generate the rustbgpd_pb2 / rustbgpd_pb2_grpc stubs with the grpc_tools.protoc
command in README.md before running this, and run it from this directory.
"""

import argparse
import sys
import threading

import grpc

# Generated by grpc_tools.protoc; deliberately not committed. See README.md.
import rustbgpd_pb2
import rustbgpd_pb2_grpc
from explain import add_connection_arguments, connect, describe, parse_prefix


def watch(channel: grpc.Channel, seconds: float, sink: list[str]) -> None:
    """Collect event summaries until the stream deadline expires.

    Deadline expiry is the normal exit: WatchEvents is an open-ended server
    stream, so the caller's deadline is what bounds it.
    """
    stub = rustbgpd_pb2_grpc.EventServiceStub(channel)
    try:
        for event in stub.WatchEvents(rustbgpd_pb2.WatchEventsRequest(), timeout=seconds):
            event_type = rustbgpd_pb2.BgpEventType.Name(event.event_type)
            prefix = f" {event.prefix}/{event.prefix_length}" if event.prefix else ""
            sink.append(f"{event_type}{prefix} {event.summary}".strip())
    except grpc.RpcError as error:
        if error.code() is not grpc.StatusCode.DEADLINE_EXCEEDED:
            sink.append(f"stream ended: {describe(error)}")


def run(channel: grpc.Channel, args: argparse.Namespace) -> None:
    address, length = parse_prefix(args.prefix)

    health = rustbgpd_pb2_grpc.ControlServiceStub(channel).GetHealth(
        rustbgpd_pb2.HealthRequest(), timeout=args.timeout
    )
    print(
        f"healthy={health.healthy} version={health.daemon_version} "
        f"uptime={health.uptime_seconds}s peers={health.active_peers} "
        f"routes={health.total_routes}"
    )

    events: list[str] = []
    watcher = threading.Thread(target=watch, args=(channel, args.watch_seconds, events))
    watcher.start()

    # No try/finally around the pair: a failed AddPath leaves nothing to clean
    # up, and wrapping it would report the cleanup call's status instead of the
    # one that actually failed. A failed DeletePath must surface as itself,
    # because it means the route is still originated.
    injection = rustbgpd_pb2_grpc.InjectionServiceStub(channel)
    injection.AddPath(
        rustbgpd_pb2.AddPathRequest(
            prefix=address,
            prefix_length=length,
            next_hop=args.next_hop,
            origin=0,  # ORIGIN: 0 = IGP, 1 = EGP, 2 = INCOMPLETE.
        ),
        timeout=args.timeout,
    )
    print(f"injected {args.prefix} via {args.next_hop}")

    injection.DeletePath(
        rustbgpd_pb2.DeletePathRequest(prefix=address, prefix_length=length),
        timeout=args.timeout,
    )
    print(f"withdrew {args.prefix}")

    watcher.join()
    for line in events:
        print(f"  event {line}")
    if not events:
        print(f"  no events within {args.watch_seconds}s")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Drive a running rustbgpd the way a containerized controller would."
    )
    add_connection_arguments(parser)
    parser.add_argument("--prefix", required=True, help='Prefix to inject, e.g. "198.51.100.0/24".')
    parser.add_argument("--next-hop", required=True, help="Next hop for the injected route.")
    parser.add_argument(
        "--watch-seconds",
        type=float,
        default=3.0,
        help="Deadline for the WatchEvents stream (default: 3).",
    )
    args = parser.parse_args(argv)

    try:
        with connect(args) as channel:
            run(channel, args)
    except grpc.RpcError as error:
        print(f"{args.target}: {describe(error)}", file=sys.stderr)
        return 1
    except (OSError, ValueError) as error:
        print(f"{args.target}: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
