#!/usr/bin/env python3
"""Ask a running rustbgpd why a prefix is (or is not) advertised to a peer.

Calls RibService.ExplainAdvertisedRoute, a `sensitive_read` RPC, and prints
the export gate ladder in the order the live export path evaluates it.

Generate the rustbgpd_pb2 / rustbgpd_pb2_grpc stubs with the grpc_tools.protoc
command in README.md before running this, and run it from this directory.
"""

import argparse
import sys
from pathlib import Path

import grpc

# Generated by grpc_tools.protoc; deliberately not committed. See README.md.
import rustbgpd_pb2
import rustbgpd_pb2_grpc


class BearerTokenPlugin(grpc.AuthMetadataPlugin):
    """Attach the daemon's bearer token to every call made on the channel."""

    def __init__(self, token: str) -> None:
        self._metadata = (("authorization", f"Bearer {token}"),)

    def __call__(
        self,
        context: grpc.AuthMetadataContext,
        callback: grpc.AuthMetadataPluginCallback,
    ) -> None:
        callback(self._metadata, None)


def add_connection_arguments(parser: argparse.ArgumentParser) -> None:
    """Register the target and credential flags shared with controller.py."""
    parser.add_argument(
        "--target",
        required=True,
        help='gRPC target: "host:port" for TCP, or "unix:///var/lib/rustbgpd/grpc.sock" for UDS.',
    )
    parser.add_argument("--tls-ca", help="PEM bundle that signed the daemon's server certificate.")
    parser.add_argument("--tls-cert", help="Client certificate PEM presented for mTLS.")
    parser.add_argument("--tls-key", help="Client private key PEM for --tls-cert.")
    parser.add_argument(
        "--token-file",
        help="File holding the bearer token for a listener configured with token_file.",
    )
    parser.add_argument(
        "--timeout",
        type=float,
        default=5.0,
        help="Per-call deadline in seconds (default: 5).",
    )


def connect(args: argparse.Namespace) -> grpc.Channel:
    """Build a channel whose credentials carry the bearer token, if any.

    The token is attached as call credentials composed into the channel
    credentials, so every RPC on this channel is authenticated without any
    caller remembering to pass metadata. gRPC only ships call credentials
    over a channel with transport security, which is why a bearer token
    requires either mTLS or the local-connection credentials used for
    loopback and Unix sockets.
    """
    unix_socket = args.target.startswith("unix:")
    # Over a Unix socket gRPC defaults `:authority` to the socket path, which
    # the daemon's HTTP/2 stack rejects as a malformed authority. Any valid
    # host token works; it is never used for routing on a Unix socket.
    options = [("grpc.default_authority", "localhost")] if unix_socket else []

    call_credentials = None
    if args.token_file:
        token = Path(args.token_file).read_text(encoding="utf-8").strip()
        call_credentials = grpc.metadata_call_credentials(
            BearerTokenPlugin(token), "rustbgpd bearer token"
        )

    if args.tls_ca:
        credentials = grpc.ssl_channel_credentials(
            root_certificates=Path(args.tls_ca).read_bytes(),
            private_key=Path(args.tls_key).read_bytes() if args.tls_key else None,
            certificate_chain=Path(args.tls_cert).read_bytes() if args.tls_cert else None,
        )
    elif call_credentials is not None:
        credentials = grpc.local_channel_credentials(
            grpc.LocalConnectionType.UDS if unix_socket else grpc.LocalConnectionType.LOCAL_TCP
        )
    else:
        return grpc.insecure_channel(args.target, options=options)

    if call_credentials is not None:
        credentials = grpc.composite_channel_credentials(credentials, call_credentials)
    return grpc.secure_channel(args.target, credentials, options=options)


def describe(error: grpc.RpcError) -> str:
    """One-line rendering of a failed RPC; both halves are optional in gRPC."""
    code = error.code()
    return f"{code.name if code else 'UNKNOWN'}: {error.details() or 'no detail'}"


def parse_prefix(value: str) -> tuple[str, int]:
    """Split "192.0.2.0/24" into its address and length halves."""
    address, _, length = value.partition("/")
    if not length:
        raise ValueError(f"expected a CIDR prefix, got {value!r}")
    return address, int(length)


def explain(stub: "rustbgpd_pb2_grpc.RibServiceStub", args: argparse.Namespace) -> None:
    address, length = parse_prefix(args.prefix)
    request = rustbgpd_pb2.ExplainAdvertisedRouteRequest(
        peer_address=args.peer,
        prefix=address,
        prefix_length=length,
    )
    response = stub.ExplainAdvertisedRoute(request, timeout=args.timeout)

    decision = rustbgpd_pb2.ExplainDecision.Name(response.decision)
    print(f"{args.prefix} -> {args.peer}: {decision}")
    if response.next_hop:
        print(f"  next hop {response.next_hop} from {response.route_peer_address}")
    if response.HasField("update_group_id"):
        print(f"  update group {response.update_group_id}")

    for step in response.gates:
        verdict = rustbgpd_pb2.ExportGateVerdict.Name(step.verdict)
        detail = f" -- {step.detail}" if step.detail else ""
        print(f"  gate {step.gate}: {verdict} ({step.code}){detail}")
    for reason in response.reasons:
        print(f"  reason {reason.code}: {reason.message}")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Explain why a prefix is or is not advertised to a peer."
    )
    add_connection_arguments(parser)
    parser.add_argument("--peer", required=True, help="Neighbor address to explain the export to.")
    parser.add_argument("--prefix", required=True, help='Prefix in CIDR form, e.g. "192.0.2.0/24".')
    args = parser.parse_args(argv)

    try:
        with connect(args) as channel:
            explain(rustbgpd_pb2_grpc.RibServiceStub(channel), args)
    except grpc.RpcError as error:
        print(f"{args.target}: {describe(error)}", file=sys.stderr)
        return 1
    except (OSError, ValueError) as error:
        print(f"{args.target}: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
